### PR TITLE
Censys: PAPP-25857 Update in product vendor and app logo

### PR DESCRIPTION
**Pull request by thehappydinoa**
## Changes

- Update pre-commit hook version
- Update icons and wheel locations
- Update docs and gitignore
- Update CI

### CODE REVIEW

**Comment by thehappydinoa** [comment]
It looks as if one of the static tests is failing due to "Min Number Log Statements" however there is a common function to handle all API calls and exceptions, is there some configuration I should update?

**Comment by thehappydinoa** [comment]
Hi @mattsayar-splunk,

I seem to be having an issue with the CI not correctly picking up some of our log statements. I am getting the following error message, is there someone who would be able to assist with this issue?

```json
"Min Number Log Statements": {
        "message": "Action implementations should have at least 2 statements to any of the following logging methods: ['debug_print', 'error_print', 'save_progress', 'send_progress']. Note that logging statements appearing in loops are only counted once.",
        "success": false,
        "verbose": [
            "_lookup_certificate has too few log statements: 0",
            "_lookup_ip has too few log statements: 0",
            "_lookup_domain has too few log statements: 0",
            "_query_domain has too few log statements: 0",
            "_query_ip has too few log statements: 0"
        ]
 }
```

**Comment by mattsayar-splunk** [comment]
Hey Aidan, one of our customers' biggest requests is clearer logging, so we require at least two logging statements in an action to help folks understand what's happening. In the error message you posted, we're requiring 'debug_print', 'error_print', 'save_progress', or 'send_progress' in the methods listed. 

This helps our customers debug issues themselves without opening unnecessary support cases. Once you've added those to the methods in 'censys_connector.py' that check should be all squared away.

**Comment by thehappydinoa** [comment]
Ah understood, the issue seems to be that the CI scanner does not seem to factor in the `debug_print` commands we are using in for loops as well as inside of our error handler function. Is there something I should do differently?

**Comment by mattsayar-splunk** [comment]
Yeah, that's correct. It's simply not enough. I would at least add two self.debug_print messages in each action. Even something as straightforward as `self.debug_print("Entering _lookup_certificate")` and `self.debug_print("Exiting _lookup_certificate")` at the beginning/end of the function is _super_ helpful for our users trying to troubleshoot issues.

**Comment by dhwanis-crest** [comment]
The semgrep pipeline is failing due to cloned repo issue. Below are the results of local semgrep runs.
image
image

**Comment by thehappydinoa** [comment]
Hey @dhwanis-crest thanks for taking a look at this PR, I was having trouble getting the CI to pass.

**Comment by dhwanis-crest** [comment]
The pytest execution link: https://cd.splunkdev.com/phantom-apps/app-tests/-/pipelines/5859027

**Review by dvora-crest — APPROVED** [review]

**Review by btavethiya-crest — APPROVED** [review]

**Pull request merged**
